### ISSUE TITLE
C3 instance's destroy method does not get called when directive's scope is destroyed

### ISSUE THREAD

**Issue by joukosaastamoinen** [maxklenk/angular-chart#40]
The situation where this is most apparent is this: if charts are created and destroyed many times, window resize event listeners get left hanging, which causes resizing browser window to get progressively slower.

**Comment by joukosaastamoinen** [comment]
I already wrote a quick and dirty fix for this, but did not have time to check if this has any side-effects: https://github.com/joukosaastamoinen/angular-chart/commit/d5a2a70c4a0cde72c4afd7b5b018de84206bbe1a

**Comment by maxklenk** [comment]
You are totally right, the c3.js event listeners have to be destroyed. I will add that in the next release.

**Comment by maxklenk** [comment]
I implemented your fix by listening to the ```$destroy``` event on the scope.

```JavaScript
// Registers a $destroy listeners for cleanup purposes
//
scope.registerDestroyListener = function() {
  scope.$on('$destroy', function() {
      scope.chart.destroy();
      element.remove();
  });
};
```
