### ISSUE TITLE
fix dataset watchers for promises or other objects

### ISSUE THREAD

**Issue by arghyaju** [maxklenk/angular-chart#50]
I have set dataset properly in my controller but in the directive 'angularchart' scope has dataset,options etc are coming undefined.
Dataset is accessible in ng-repeat function in the same view.

My controller:

var SearchAppController = angular.module('SearchAppController', ['angularChart']);

SearchAppController.controller('ItemDetailController',function($scope,$http,$location,$routeParams){ 
	
		var itemID = $routeParams.itemID;
		var completeURL = "/search/price/"+itemID;
		var responsePromise = $http.get(completeURL);
		responsePromise.success(function(data, status, headers, config) {
			var historyList = data[0].history;
			$scope.dataset = historyList;
			                $scope.schema = {
			                  time: {
			                    type: 'datetime',
			                    format: '%Y-%m-%d %H:%M:%S',
			                    name: 'Date'
			                  }
			                };

			                $scope.options = {
			                  rows: [{
			                    key: 'lowestNewPrice',
			                    type: 'bar'
			                  }, {
			                    key: 'time'
			                  }],
			                  xAxis: {
			                    key: 'time',
			                    displayFormat: '%Y-%m-%d %H:%M:%S'
			                  }
			                };
			               
	
	});
});

My view:

<div ng-app>
	<div ng-controller="ItemDetailController">
  <angularchart
    dataset="dataset"
    schema="schema"
    options="options">
  </angularchart>
  </div>	

Thanks in advance!

**Comment by arghyaju** [comment]
If I dont use the callback API call and pass hardcoded values it works.

**Comment by arghyaju** [comment]
It seems data binding is happening before callback can populate the values.But I believe the dataset watcher should do the trick.Not sure why its not happening.

**Comment by arghyaju** [comment]
dataset watcher was not getting initialized because dataset was undefined initially and watcher does dataset.length.Initialized dataset to a non-blank array, now it works.Please see if it can be handled elegantly.

**Comment by maxklenk** [comment]
Thank you for reporting, the behavior is definitively wrong. I'll fix this in the next release.

**Comment by arghyaju** [comment]
Thanks Max.
