### ISSUE TITLE
Padding is not implemented

### ISSUE THREAD

**Issue by cjones26** [maxklenk/angular-chart#53]
Hello Max--first of all, thanks for the awesome project!  Secondly, I noticed padding didn't seem to be implemented and the only way I could figure a way around it was to implement it like so:

````
// Padding
//
if (scope.options.padding) {
  scope.configuration.padding = scope.options.padding;
} else {
  scope.configuration.padding = {};
}
````
Which seemed to work simply enough when I specified padding in my options like so:
````
$scope.options = {
  padding: {
    bottom: 20
  }
};
````

**Comment by maxklenk** [comment]
This option is not implemented yet, but it will be added with the other configuration parameters in the 0.3 version of angular-chart

**Comment by sebastianhenneberg** [comment]
As part of the recent [0.3.0](https://github.com/maxklenk/angular-chart/releases/tag/0.3.0) release, angular-chart now [supports the full C3 API](https://github.com/maxklenk/angular-chart#chart). Have a look at this [graFiddle](http://grafiddle.it/5699257587728384) on how to set `margin.bottom`. Please check the [upgrade guide](https://github.com/maxklenk/angular-chart#upgrade-02x-to-030) for upgrading from 0.2.x to 0.3.0.
