### ISSUE TITLE
X Axis Tick Count

### ISSUE THREAD

**Issue by alydubel** [maxklenk/angular-chart#54]
Is it possible to set the x-axis tick count ?

Example: http://c3js.org/samples/axes_x_tick_count.html

**Comment by maxklenk** [comment]
This option is not implemented yet, but it will be added with the other configuration parameters in the 0.3 version of angular-chart

**Comment by maxklenk** [comment]
You can now set the tick count in the `chart` part of the options.
See a working example in this [grafiddle](http://grafiddle.it/5639274879778816).
