### ISSUE TITLE
Chart not rendering on IE 8/7

### ISSUE THREAD

**Issue by sagar-mindstix** [maxklenk/angular-chart#59]
I have added angularJS1.2.28 instead of angularJS 1.3.x.  Chart is working fine till IE 9 but It is not support for IE 8/7. Is there any pollyfill for supporting chart on IE 8/7?

**Comment by maxklenk** [comment]
As you already saw, AngularJS dropped the support for IE below version 9. I have not tested the support of these browsers either. You can try the following for IE 8 and in a second step for IE 7 too:
- [ ] Ensure that angular-chart is working with AngularJS 1.2.x in other browsers
- [ ] Ensure that c3.js is working in IE 8 (http://c3js.org/)
- [ ] Follow the [old AngularJS documentation](https://code.angularjs.org/1.2.27/docs/guide/ie) to support custom tags
- [ ] Report back how it is going

**Comment by maxklenk** [comment]
@sagar-mindstix have you tried some of this steps?
