### ISSUE TITLE
Misplaced Tooltip

### ISSUE THREAD

**Issue by eckyputrady** [maxklenk/angular-chart#67]
In the screenshot below, I hover on bottom right chart, however, the tooltip shown at the top left

![screen shot 2015-04-06 at 3 40 03 pm](https://cloud.githubusercontent.com/assets/1640959/7002355/7f878808-dc73-11e4-81c2-ce79a32a97f9.png)

I fixed it by giving `angularchart` directive a `position: relative` style.

Shouldn't `angularchart` directive have `position: relative` style by default?

**Comment by maxklenk** [comment]
Hi @eckyputrady,
thank you for mentioning this, other people had the same problem. In the next release the css file will be part of the main files you automatically include with bower. The used styles are set [in there](https://github.com/maxklenk/angular-chart/blob/develop/angular-chart.css#L593).
