### ISSUE TITLE
yAxis min/max options does not work

### ISSUE THREAD

**Issue by eckyputrady** [maxklenk/angular-chart#68]
Here's an example `options` input:

```
    $scope.options = {
      rows: [{
        key: 'one',
        type: 'bar'
      }, {
        key: 'two',
        type: 'bar'
      }, {
        key: 'three',
        type: 'bar'
      }],
      xAxis: {
        key: 'atTime',
        displayFormat: '%Y-%m-%d %H:%M:%S'
      },
      yAxis: {
        max: 400,
        min: -400,
        label: "Number of contributions"
      }
    }
```

everything works correctly except min / max.

The docs also state that the value for yAxis' min/max is a string. Shouldn't those be number?

**Comment by eckyputrady** [comment]
Oops, my bad. I'm reading docs in `develop` branch but using version `0.2.6`

**Comment by nairys** [comment]
@eckyputrady were you able to get yAxis min working?

**Comment by eckyputrady** [comment]
Yes. But after using code from `develop` branch at that time.
