### ISSUE TITLE
Ability to set tick culling & multiline?

### ISSUE THREAD

**Issue by mfollett** [maxklenk/angular-chart#69]
Is there a way to configure [tick culling](http://c3js.org/samples/axes_x_tick_culling.html) or [multiline/rotation](http://c3js.org/samples/axes_x_tick_rotate.html) for the axes?

If not, what would be a good interface to do so? I'd be happy to implement it, I'm just not sure how best to expose it.

**Comment by mindontheblink** [comment]
I would like to see these options exposed as well.   Have you had any luck writing your own workaround?

**Comment by mfollett** [comment]
My workaround was to modify angular-chart to expose tick options. I didn't publicize this, but I don't think there'd be any reason for me not to. If there is interest in using it I can publish the fork

**Comment by mindontheblink** [comment]
I would definitely be interested.  Thanks!

**Comment by maxklenk** [comment]
Please provide a pull request, so we can merge your additions into the main project.

**Comment by mindontheblink** [comment]
Has there been any movement on getting this merged into the project?  I will have to expose the tick options myself today if not.

**Comment by mfollett** [comment]
I put [my branch](mfollett/angular-chart/tree/addTickOptions) up a couple
of minutes ago, but I haven't put up a pull request as `npm install` isn't
succeeding for me so I cannot put up a pull request. Hopefully I'll have
this resolved shortly & will be able to do that.

**Comment by mindontheblink** [comment]
Thanks, @mfollett!  This should get me by until it is merged in officially.

**Comment by mfollett** [comment]
@mindontheblink commit a3b6a3ec602352c719e1835731823debd76f7f2d passed all the tests so I'd use that one.

**Comment by maxklenk** [comment]
@mfollett thank you for contributing to this project and helping others by doing so.
