### ISSUE TITLE
Labels format

### ISSUE THREAD

**Issue by nestorneto** [maxklenk/angular-chart#70]
any chance to implement:

```javascript
labels: {
  format: function (value, ratio, id) {
    return d3.format('$')(value);
  }
},

**Comment by maxklenk** [comment]
Maybe you can solve this using the axis display format:
https://github.com/maxklenk/angular-chart#xaxisdisplayformat--string--function--see-example

On the long run the post- and pre-fixes defined in the schema will do the job.

**Comment by maxklenk** [comment]
Hi @nestorneto,
with the new release there are three ways to specify this in as much detail as you want:

#### 1. `dimension.prefix`
The API allows you to specify a prefix for a dimension which is then applied to all occurrences of the dimension (tooltips, labels, axis,...). Have a look at this [grafiddle](http://grafiddle.it/5767281011326976) to see how it works.

#### 2. `dimension.displayFormat`
Similar to the `prefix` you can add your custom function to handle the formatting, you could simply pass the d3 format function to accomplish the currency formatting:
```javaScript
dimensions: {
  data1: {
    label: true,
    function: d3.format('$')
  }
}
```

#### 3. native c3-configuration
The `chart` object inside the options gives you direct access to the c3-configuration. This would allow you to set a specific format only for the labels and noting else.
