### ISSUE TITLE
Chart option interaction not customizable

### ISSUE THREAD

**Issue by belens** [maxklenk/angular-chart#72]
You cannot set the interaction option (c3js.org/reference.html#interaction-enabled). Haven't found the time to dive into the code and create a pull request.

**Comment by maxklenk** [comment]
Hey @belens, with the upcoming 0.3.0 release #55 of  angular-chart all c3 options will be included - please wait until the documentation is ready.

**Comment by maxklenk** [comment]
The [0.3.0](https://github.com/maxklenk/angular-chart/releases/tag/0.3.0) release is out, angular-chart now [supports the full C3 API](https://github.com/maxklenk/angular-chart#chart). Have a look at this [graFiddle](http://grafiddle.it/5677751478517760) which shows how to disable all interactions in angular-chart.
Please check the [upgrade guide](https://github.com/maxklenk/angular-chart#upgrade-02x-to-030) for upgrading from 0.2.x to 0.3.0.
