### ISSUE TITLE
Label placement

### ISSUE THREAD

**Issue by btm1** [maxklenk/angular-chart#73]
Is there a way to specify where the label is? Right now they appear inside of the chart area overlapping the chart and small at the top... this is very strange. Is there a way to say: "i want my labels to the left of the Y axis and below the X axis and centered?

**Comment by maxklenk** [comment]
Currently there is no way to choose different label placement positions, when integrating more of the c3 api, the following options will be present: http://c3js.org/samples/axes_label_position.html

**Comment by mindontheblink** [comment]
There might not be an official way of doing this with this Angular directive's API, but I found the following to work for me when defined in the chart options using the author's directive:

         yAxis: {
                    label: {
                        text: 'Text here',
                        position: 'outer-middle'
                    }
                }


You can set position value to one of 6 values the author linked to above.(http://c3js.org/samples/axes_label_position.html)

I haven't tried the X-Axis yet, but I would imagine it would work as well.

**Comment by btm1** [comment]
@mindontheblink just what i was looking for thanks. This is solved. This should be put in the documentation on the directive side as well so people know.

**Comment by maxklenk** [comment]
The [0.3.0](https://github.com/maxklenk/angular-chart/releases/tag/0.3.0) release is out, angular-chart now [supports the full C3 API](https://github.com/maxklenk/angular-chart#chart). Have a look at this [graFiddle](http://grafiddle.it/5651124426113024) to see where to add the label position now.
Please check the [upgrade guide](https://github.com/maxklenk/angular-chart#upgrade-02x-to-030) for upgrading from 0.2.x to 0.3.0.
