### ISSUE TITLE
Grid Lines Support

### ISSUE THREAD

**Issue by mindontheblink** [maxklenk/angular-chart#75]
There doesn't seem to be an option to create X or Y axis grid lines as shown on the c3js website. 

http://c3js.org/samples/options_gridline.html

What would be the best way of achieving this using this directive?  Thanks!

**Comment by maxklenk** [comment]
Hey @mindontheblink, with the upcoming 0.3.0 release #55 of  angular-chart all c3 options will be included - please wait until the documentation is ready.

**Comment by mindontheblink** [comment]
Thanks, @maxklenk! I will be sure to test this out in version 0.3.0.  

Your directive has been very helpful for my project -- your support is greatly appreciated!

**Comment by maxklenk** [comment]
The [0.3.0](https://github.com/maxklenk/angular-chart/releases/tag/0.3.0) release is out, angular-chart now [supports the full C3 API](https://github.com/maxklenk/angular-chart#chart). Have a look at this [graFiddle](http://grafiddle.it/5695159920492544) on how to add gridlines.
Please check the [upgrade guide](https://github.com/maxklenk/angular-chart#upgrade-02x-to-030) for upgrading from 0.2.x to 0.3.0.
