### ISSUE TITLE
Change radius of points in scatter chart

### ISSUE THREAD

**Issue by lmayren** [maxklenk/angular-chart#78]
Using angular-chart is it possible to change the radius of the points (in relation to the data value) in the scatter chart in order to create a scatter bubble chart? Looking at the C3 docs it should be possible using the point.r property.

http://c3js.org/reference.html#point-r

**Comment by maxklenk** [comment]
Hey @lmayren, with the upcoming 0.3.0 release #55 of  angular-chart all c3 options will be included - please wait until the documentation is ready.

**Comment by maxklenk** [comment]
With the new version (0.3.0) of angular-chart, the point radius can now be configured.

Check out this [grafiddle](http://grafiddle.it/5151213049872384).
