### ISSUE TITLE
Data Order

### ISSUE THREAD

**Issue by linyatis** [maxklenk/angular-chart#79]
Is there any support for data order? (http://c3js.org/samples/data_order.html)
If it isn't, how could I do this using angular-chart?

**Comment by maxklenk** [comment]
With the new version (0.3.0) of angular-chart, data order is now supported.

Check out this [grafiddle](http://grafiddle.it/5679413765079040).

**Comment by linyatis** [comment]
Great, @maxklenk! Thanks for your help here.
