### ISSUE TITLE
Rotate axis support to create row charts

### ISSUE THREAD

**Issue by peibol16** [maxklenk/angular-chart#80]
Actually row charts like next example are not supported.

http://c3js.org/samples/axes_rotated.html

**Comment by maxklenk** [comment]
The functionality will come, [release 0.3.0](https://github.com/maxklenk/angular-chart/tree/feature/0.3.0) is on its way and will support the full c3 API. I am currently working on an upgrade guide from the current version. Feel free to try the feature [branch](https://github.com/maxklenk/angular-chart/tree/feature/0.3.0) already.

**Comment by btm1** [comment]
you could actually still just do this via .chart.axis directly through the api and it still works

**Comment by maxklenk** [comment]
Like @btm1 said, it is now possible to use rotated axes because the 0.3.0 version has been released. Check out this [grafiddle](http://grafiddle.it/5714163003293696) to see how it works.
