### ISSUE TITLE
TypeError: (intermediate value)[type] is not a function

### ISSUE THREAD

**Issue by CiscoKidxx** [maxklenk/angular-chart#81]
Full code here:
http://stackoverflow.com/questions/30631110/typeerror-intermediate-valuetype-is-not-a-function

I am trying to display a simple chart following the guide here: http://jtblin.github.io/angular-chart.js/

I am using sails.js, angular, bootstrap and angular-chart.js

When I load the app, I get a blank image where a chart should be. I see this error in chrome dev tools:

TypeError: (intermediate value)[type] is not a function
at createChart (angular-chart.js:175)
at Object.fn (angular-chart.js:118)
at Scope.$get.Scope.$digest (angular.js:14308)
at Scope.$get.Scope.$apply (angular.js:14571)
at bootstrapApply (angular.js:1455)
at Object.invoke (angular.js:4203)
at doBootstrap (angular.js:1453)
at bootstrap (angular.js:1473)
at angularInit (angular.js:1367)
at angular.js:26304
Please forgive me but I don't know why that error is popping.

I have tried endless amounts of variations of the code below and feel this version is the closest I have gotten to a working sample.

**Comment by maxklenk** [comment]
Hey, your referencing to a guide which is based on an other library. The guide is for https://github.com/jtblin/angular-chart.js not for https://github.com/maxklenk/angular-chart.

This library here is based ond d3.js instead of chart.js.

**Comment by suryadeepchatterjee3107** [comment]
@maxklenk I'm having the same problem. I tried using d3.js instead of chart.js, still, it didn't work.

**Comment by suryadeepchatterjee3107** [comment]
List of errors:
ionic.bundle.js:25642 TypeError: (intermediate value)[e] is not a function
    at d (angular-chart.min.js:1)
    at Object.fn (angular-chart.min.js:1)
    at Scope.$digest (ionic.bundle.js:28995)
    at Scope.$apply (ionic.bundle.js:29263)
    at ionic.bundle.js:31030
    at completeOutstandingRequest (ionic.bundle.js:18706)
    at ionic.bundle.js:18978

**Comment by craniodev** [comment]
It's working in my case

    <link rel="stylesheet" href="http://jtblin.github.io/angular-chart.js/dist/angular-chart.css" />
    <script src="http://jtblin.github.io/angular-chart.js/bower_components/Chart.js/Chart.js"></script>
    <script src="http://jtblin.github.io/angular-chart.js/dist/angular-chart.js"></script>

**Comment by maxklenk** [comment]
@craniodev you do not use the library of this repository, because you use `angular-chart.js` which is based on `Chart.js`. To use `angular-chart` the library `d3.js` has to be included.

@suryadeepchatterjee3107 can you please post your bower file or the links to the files to include so I can check if something does not match right.

**Comment by suryadeepchatterjee3107** [comment]
https://github.com/suryadeepchatterjee3107/angul/tree/master/www @maxklenk

**Comment by suryadeepchatterjee3107** [comment]
please check the app.js and index.html, i have created this demo project to check angular charts.

**Comment by maxklenk** [comment]
@suryadeepchatterjee3107 I had a look at your code, you are using Chart.js and https://github.com/jtblin/angular-chart.js which is the right combination. Please ask in their [repository](https://github.com/jtblin/angular-chart.js) how to fix your problem.

**Comment by suryadeepchatterjee3107** [comment]
oh! okay, Thank you! @maxklenk

**Comment by suryadeepchatterjee3107** [comment]
BTW, Thank you @craniodev , it worked for me.

**Comment by jsbimra** [comment]
Using without minification code it worked for me too, but with Chart.min.js and angular-chart.min.js its give the same error denoted here. 
does anybody used both the files with minification's.?

**Comment by suryadeepchatterjee3107** [comment]
@jsbimra I would assume that you have changed the links from  "angular-chart.js" to "angular-chart.min.js" and yet you are getting those errors. To solve it, please make sure you are using the latest angular-chart.js 1.0.0-alpha version which is compatible with chart.js 2.0.

**Comment by jsbimra** [comment]
@suryadeepchatterjee3107  
Using following version of  
https://raw.githubusercontent.com/jtblin/angular-chart.js/chartjs-2.0/dist/angular-chart.min.js
with minify version  
Chart.js
 * http://chartjs.org/
 * Version: 2.0.2

Got the following error : Chart.min.js:12 Uncaught TypeError: a is not a function

**Comment by suryadeepchatterjee3107** [comment]
@jsbimra can you please post the <script src> tag content!
correct me if I am wrong. you have downloaded the Chart.js and angular-chart.min.js and copied it in one of your js files. Now, you are linking the local files right?

**Comment by suryadeepchatterjee3107** [comment]
@jsbimra  correct me if I am wrong. you have downloaded the Chart.js and angular-chart.min.js and copied it in one of your js files. Now, you are linking the local files right?

**Comment by jsbimra** [comment]
Yes. 
This is how i have included
Version: 2.0.2`<script src="libs/angular-chart/Chart.min.js"></script> `
Copied from source mentioned above` <script src="libs/angular-chart/angular-chart-v1alpha.min.js"></script>`

**Comment by suryadeepchatterjee3107** [comment]
Hey @jsbimra , you need to use chart version 1.x. It will work fine with 1.x. 
For some reason, the wrapper is not supporting chart version 2.x .

**Comment by jsbimra** [comment]
hmm.. can't use new feature's of Chart version 2.0 with angular-chart.js :(

**Comment by avadhanij** [comment]
So this is still open? Or needs a new bug?
