### ISSUE TITLE
angular.merge is not a function

### ISSUE THREAD

**Issue by btm1** [maxklenk/angular-chart#83]
the first thing i see is this:

There is no such thing as angular.merge only extend.  What's the deal? I can't get this to work.

**Comment by btm1** [comment]
just change line 529 to

angular.extend(
        this.configuration,
        this.options.chart
      );

**Comment by sebastianhenneberg** [comment]
Hi btm1,

[angular.merge](https://docs.angularjs.org/api/ng/function/angular.merge) is a new function of the most recent [Angular 1.4 release](https://github.com/angular/angular.js/blob/master/CHANGELOG.md#140-jaracimrman-existence-2015-05-26). It provides the functionality to **deeply** merge to or more objects.

Please note the difference between `angular.extend` and `angular.merge` from the docs:
> Unlike extend(), merge() recursively descends into object properties of source objects, performing a deep copy.

If you integrate Angular 1.4, everything should work fine.

**Comment by btm1** [comment]
gottcha... not everyone is ready to upgrade to 1.4 yet this is a notable fallback so at least angularChart doesn't crash:

angular.merge = function (s1,s2) {
    return $.extend(true,s1,s2);
};

**Comment by maxklenk** [comment]
Yes I was thinking about adding a fallback. Your solution only works with jquery, I will search for a pure javascript solution

**Comment by maxklenk** [comment]
We will add https://github.com/KyleAMathews/deepmerge in the next release.

**Comment by maxklenk** [comment]
It is done! I added a fallback solution for angular < 1.4.0, so you should be able to remove your own fix when updating to angular-chart 0.3.1
