### ISSUE TITLE
horizontal bar chart

### ISSUE THREAD

**Issue by btm1** [maxklenk/angular-chart#84]
Is there a way to make a horizontal bar chart? I didn't see that specified in the options.

**Comment by btm1** [comment]
if I assign a property that represents a scale to the Y axis and the assign a property that represents the bars to the X axis it should make a horizontal bar chart...and right now it doesn't.

**Comment by sebastianhenneberg** [comment]
Hi btm1,

have you tried the `axis.rotated` option? Check out this [graFiddle](http://grafiddle.it/5638830484881408) and have a look at the right sidebar.

**Comment by btm1** [comment]
yeah i just figured out that I could do that. So i guess this is closed? so what's happening here I'm a bit confused is this project basically rewriting their existing C3 api inside of the confines of the dimensions property inside of the options that get passed? If so why? Why not just use the existing API and make it stateful?

**Comment by maxklenk** [comment]
That true angular-chart wraps the c3 api in an angular directive. If you want you can just use `options.chart` and save your complete c3-configuration in there. `options.state` can then be used, so your chart will be stateful.
`options.dimensions`is a addition we added to simplify the API of c3, for example defining a displayformat for one dimension automatically updates the axes, tooltips and labels. In c3 you have to update it in four places on your own. It can be seen as [syntactic sugar](http://en.wikipedia.org/wiki/Syntactic_sugar) which can be used but doesn't has to be used.
