### ISSUE TITLE
Bring back the old website with examples

### ISSUE THREAD

**Issue by btm1** [maxklenk/angular-chart#86]
I'm finally trying to integrate this into my project and the old website was very helpful with the live editor and many examples for different chart types.  The new website with the very limited git documentation isn't very helpful in figuring things out.

**Comment by sebastianhenneberg** [comment]
Hi btm1, you are totally right. But we did that with intention. ;-)

From now on, we want to encourage to test and discover angular-chart using [graFiddle](http://grafiddle.it/). graFiddle runs the latest version of angular-chart and the charts can be manipulated in real-time similar to the old demo page. Unfortunately, we did not had enough time to create samples on the last code camp. We will add them soon. Until then, feel free to play around with graFiddle to explore angular-chart.

**Comment by btm1** [comment]
oh that's perfect thanks

**Comment by sebastianhenneberg** [comment]
You're welcome! Feedback of any kind regarding graFiddle can be directed at https://github.com/GraFiddle/grafiddle

**Comment by Phisherman** [comment]
Hi,

I just visited grafiddle.it. Where are the examples?
