### ISSUE TITLE
dimensions "label" doesn't do anything?

### ISSUE THREAD

**Issue by btm1** [maxklenk/angular-chart#91]
The Label property in dimensions either has confusing documentation or doesn't do anything.  If you specify label true nothing happens and even if you do specify true there is it getting the definition for the label from? is it dimensions.name? do you need to specify the label name someplace else? Is it state-full can I change it on the fly? 

Essentially I have two y and y2 axis and I need to label these axises and I'm not sure how to go about that.

**Comment by maxklenk** [comment]
You are right, the label option can be confusing at the moment. The `label`key in `dimensions` works only for [data labels](http://c3js.org/samples/data_label.html) at the moment.

We will work on a solution to include axis labels with this option too. In the meanwhile you are able to configure them using the c3-configuration. Have a look at this [grafiddle](http://grafiddle.it/5757334940811264) to see how it is done. For sure all values get synced with the chart when changing  them.

**Comment by btm1** [comment]
thanks @maxklenk I figured it out.  So just curious though why not not just declare everything through c3 config?  Eventually is the idea that you will phase out options.chart (c3 config) once you dimensions supports everything that c3 config does?  namely dimensions has a more intuitive structure for declaring c3 config options than the original?

**Comment by maxklenk** [comment]
The `dimensions` will not replace the whole c3-configuration, earlier versions of angular-chart tried to provide an own api for everything but I doesn't make sense to just rewrite everything.
I focus on providing a easier way to set c3-configurations using the dimensions. The `label` key is a nice example for this because it allows me to set different configurations based on the context.

**Comment by btm1** [comment]
@maxklenk makes sense! thanks for the explanation. This project is very exciting to me. I currently work as a ux/developer for data visualization and if my schedule frees up I may try to help contribute to this :) I build a similar but internal directive statefull integration between D3 and angular without c3 in the middle some time ago.

**Comment by maxklenk** [comment]
I had a look at this in the code, the axis labels can not be defined in the dimensions, because multiple dimensions can stand for the same `y`-axis. Therefore the native c3 solution used in the [grafiddle](http://grafiddle.it/5757334940811264) will be still the best solution.
