### ISSUE TITLE
Dynamic resize

### ISSUE THREAD

**Issue by warapitiya** [maxklenk/angular-chart#94]
How do I dynamically resize the chart? I tried using

```json
chart: {
   "size":{
      "width": $scope.chartWidth
   }
}
```
but this won't work. any help?

Also tried $scope.options.resize() :-1:

**Comment by maxklenk** [comment]
Hi @warapitiya,
the problem here is that angular does not create a reference to `$scope.chartWidth` as you may expect, because it is only a number or string and not an object.
It will work if you reference an object instead, see this [example](http://plnkr.co/edit/TDzlGY).

```javaScript
// dynamic chart width
$scope.size = {
  width: 200
};

// chart options
$scope.options = {
  chart: {
    size: $scope.size
  }
};
```

**Comment by sebastianhenneberg** [comment]
It is a limitation of the JavaScript language which occurs whenever you work with scopes. Check the [Understanding Scopes article](https://github.com/angular/angular.js/wiki/Understanding-Scopes) from the AngularJS Wiki for more information.
